### PR TITLE
Add Timeout to Proxy struct.

### PR DESCRIPTION
**Pull request by dajohi**
This allows the caller to set the dial timeout when using
DialContext.

### CODE REVIEW

**Review by dnldd — APPROVED** [review]
Nice.

**Comment by jrick** [comment]
Can't the timeout already be accomplished with the context? also the api that doesn't take any context isn't using this timeout, when this seems like the api where it would really be necessary.

**Comment by dnldd** [comment]
Currently the api allows one or the other (context or timeout). It should be possible to set the timeout while dialing with a context, this allows that.

**Comment by jrick** [comment]
Does this not already work?

```
ctx, cancel := context.WithTimeout(ctx, timeout)
defer cancel()
conn, err := proxy.DialContext(ctx, network, addr)
```

**Comment by dnldd** [comment]
Ah damn, I thought the Dialer's `Timeout` was the idle timeout for connections created through it. It's not, it's the connection timeout instead. My bad @dajohi

**Comment by jrick** [comment]
Still need this or should be closed?

**Comment by dnldd** [comment]
Nope, close it.

**Pull request closed without merging**
